
### .github/workflows/dependabot_pr.yml
### This workflow doesn't have access to secrets and has a read-only token
name: Dependabot PR Check
on:
  pull_request

jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Action failed')

  
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github.event.number) }}
#         run: echo "$GITHUB_CONTEXT"
