name: "Dependabot Automerge"

on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types: 
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest

#     if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
#       - name: automerge
#         run: |
#         uses: actions/github-script@0.2.0
#         with:
#           script: |
#             github.pullRequests.createReview({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: context.payload.pull_request.number,
#               event: 'APPROVE'
#             })
#             github.pullRequests.merge({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: context.payload.pull_request.number
#             })
#           github-token: ${{secrets.GITHUB_TOKEN}}
