name: "Dependabot Automerge"

on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types: 
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
#     if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dump GitHub context
        env:
          pull_request_number: ${{ toJSON(github.event.workflow_run.pull_requests[0].number) }}
        run: echo ${{ toJSON(github.event.workflow_run.pull_requests[0].number) }}
      - uses: actions/github-script@v3
        with:
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: ${{env.pull_request_number}},
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: ${{env.pull_request_number}},
              merge_method: 'squash'
            })
          github-token: ${{github.token}}
