name: "Dependabot Automerge"

on:
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types: 
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo ${{ toJSON(github.event.workflow_run.pull_requests) }}
#     if: github.actor == 'dependabot[bot]'
#     steps:
#       - uses: actions/github-script@v3
#         with:
#           script: |
#             github.pulls.createReview({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: 6,
#               event: 'APPROVE'
#             })
#             github.pulls.merge({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: 6,
#               merge_method: 'squash'
#             })
#           github-token: ${{github.token}}
